# Generated by Django 5.0.6 on 2024-06-09 03:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_rename_assigment_assignment'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='courses',
        ),
        migrations.AddField(
            model_name='student',
            name='courses',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, related_name='students', to='courses.course'),
            preserve_default=False,
        ),
    ]
