# Generated by Django 5.0.6 on 2024-06-17 03:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_remove_content_course_rename_title_course_name_and_more'),
        ('users', '0002_remove_student_courses_student_courses'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Teacher',
        ),
        migrations.AlterField(
            model_name='student',
            name='courses',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='students', to='courses.course'),
        ),
    ]
