# Generated by Django 5.0.6 on 2024-06-17 03:45

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_rename_assigment_assignment'),
        ('users', '0002_remove_student_courses_student_courses'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='content',
            name='course',
        ),
        migrations.RenameField(
            model_name='course',
            old_name='title',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='course',
            name='id',
        ),
        migrations.AddField(
            model_name='course',
            name='code',
            field=models.CharField(default='', max_length=10, primary_key=True, serialize=False, unique=True),
        ),
        migrations.CreateModel(
            name='NotasAlumnoPorCurso',
            fields=[
                ('id_nota', models.CharField(max_length=100, primary_key=True, serialize=False, unique=True)),
                ('nota', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('id_alumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student', to='users.student')),
                ('id_curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='curso', to='courses.course')),
            ],
        ),
        migrations.DeleteModel(
            name='Assignment',
        ),
        migrations.DeleteModel(
            name='Content',
        ),
    ]
